"""
pr_generator.py — Generates GitHub-style Pull Request summaries.
Uses Google Gemini (free API).
"""
import json
import os
import logging
from datetime import datetime

logger = logging.getLogger("autopm.pr")

PR_PROMPT = """You are a senior developer writing a GitHub Pull Request. Generate a comprehensive PR summary based on the following:

Task: {task_title}
Description: {description}
Code File: {filename} ({language})
Review Score: {review_score}/10
Review Verdict: {verdict}

Respond with ONLY a valid JSON object (no markdown, no code fences):
{{
  "pr_title": "Clear PR title following conventional commits (e.g., 'fix: resolve upload 500 error')",
  "pr_body": "Full PR description in markdown format with sections: ## Summary, ## Changes, ## Testing, ## Screenshots (if applicable)",
  "labels": ["List of GitHub labels"],
  "reviewers": ["Suggested reviewers based on component"],
  "branch_name": "suggested-branch-name",
  "breaking_changes": false,
  "migration_required": false
}}
"""


def _mock_generate_pr(task: dict, code_output: dict, review: dict) -> dict:
    """Generate a mock PR summary."""
    title = task.get("task_title", "Untitled Task")
    labels = task.get("labels", [])
    filename = code_output.get("filename", "unknown.py")
    language = code_output.get("language", "python")
    verdict = review.get("verdict", "Approved")
    score = review.get("overall_score", 8)
    review_summary = review.get("summary", "")

    # Determine PR prefix
    if "bug" in labels:
        prefix = "fix"
        branch_prefix = "fix"
    elif "performance" in labels:
        prefix = "perf"
        branch_prefix = "perf"
    else:
        prefix = "feat"
        branch_prefix = "feature"

    pr_title = f"{prefix}: {title.lower().replace('fix: ', '').replace('feature: ', '').replace('optimize: ', '')}"
    branch = f"{branch_prefix}/{title.lower().replace(' ', '-').replace(':', '')[:40]}"

    pr_body = f"""## Summary

{task.get('description', 'No description available.')}

## Changes

- **File**: `{filename}` ({language})
- **Type**: {task.get('labels', ['general'])[0].title()}
- **Estimated Effort**: {task.get('estimated_effort', 'Medium')}

### What Changed
{code_output.get('explanation', 'Implementation as per task requirements.')}

## Code Review

| Metric | Value |
|--------|-------|
| **Score** | {score}/10 |
| **Verdict** | {verdict} |

{review_summary}

### Review Issues
"""

    for issue in review.get("issues", []):
        severity = issue.get("severity", "Info")
        emoji = {"Critical": "🔴", "Warning": "🟡", "Info": "🔵"}.get(severity, "⚪")
        pr_body += f"\n{emoji} **{severity}**: {issue.get('description', '')}"
        pr_body += f"\n  - 💡 {issue.get('suggestion', '')}\n"

    pr_body += f"""
## Acceptance Criteria

"""
    for criterion in task.get("acceptance_criteria", []):
        pr_body += f"- [ ] {criterion}\n"

    pr_body += f"""
## Testing

- [ ] Unit tests pass
- [ ] Integration tests pass
- [ ] Manual testing completed
- [ ] No regression in existing functionality

## Deployment Notes

- No breaking changes
- No database migrations required
- Standard deployment process

---
*Generated by AutoPM at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*
"""

    return {
        "pr_title": pr_title,
        "pr_body": pr_body,
        "labels": labels,
        "reviewers": ["tech-lead", "senior-dev"],
        "branch_name": branch,
        "breaking_changes": False,
        "migration_required": False,
    }


def generate_pr(task: dict, code_output: dict, review: dict) -> dict:
    """
    Generate a GitHub-style Pull Request summary.
    Uses Google Gemini (free API).

    Args:
        task: Output from generate_task().
        code_output: Output from generate_code().
        review: Output from review_code().

    Returns:
        Dictionary with pr_title, pr_body, labels, reviewers, branch_name, etc.
    """
    api_key = os.getenv("GEMINI_API_KEY")
    model_name = os.getenv("GEMINI_MODEL", "gemini-2.0-flash")

    if not api_key:
        logger.info("No Gemini API key — using mock PR generation")
        return _mock_generate_pr(task, code_output, review)

    try:
        import google.generativeai as genai

        genai.configure(api_key=api_key)
        model = genai.GenerativeModel(model_name)
        response = model.generate_content(
            PR_PROMPT.format(
                task_title=task.get("task_title", ""),
                description=task.get("description", ""),
                filename=code_output.get("filename", ""),
                language=code_output.get("language", "python"),
                review_score=review.get("overall_score", 0),
                verdict=review.get("verdict", ""),
            ),
            generation_config=genai.GenerationConfig(
                temperature=0.4,
                max_output_tokens=1000,
            ),
        )
        raw = response.text.strip()
        # Strip markdown code fences if present
        if raw.startswith("```"):
            raw = raw.split("\n", 1)[1] if "\n" in raw else raw[3:]
            raw = raw.rsplit("```", 1)[0]
        result = json.loads(raw.strip())
        logger.info("PR generated: %s", result.get("pr_title"))
        return result

    except Exception as e:
        logger.error("Gemini PR generation failed: %s — using mock", str(e))
        return _mock_generate_pr(task, code_output, review)
